name: Hello World Default
on: [workflow_dispatch]
jobs:
  Hello-World-Job:
    # Use the environmet specified in CodeBuild
    runs-on:
      - codebuild-github-runner-codeconnection-test-${{ github.run_id }}-${{ github.run_attempt }}
    defaults:
      run:
        shell: bash
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      # Testing
      # --load is required in docker build, or push to ECR and run from ECR
      - run: |
          echo "Hello World"
          ls -la
          echo Logging in to Amazon ECR...
          aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com
          docker build -t helloworld:latest ./helloworld 
          docker tag helloworld:latest $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/helloworld:latest
          docker run $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/helloworld:latest echo "Hello, World from github action workflow!"
          docker images
