name: Hello World Fleet
on: [workflow_dispatch]
jobs:
  Hello-World-Job:
    # Override the environment setup in CodeBuild
    runs-on:
      - codebuild-github-runner-codeconnection-test-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:aws-tf-eks-demo-fleet
    steps:
      - run: echo "Hello World"
